---

# Set up conda channels:
- name: 'miniconda install condarc'
  template:
    src: 'condarc.j2'
    dest: "{{ miniconda_install.user_home  }}/.condarc"
    owner: "{{ miniconda_install.user }}"
  when: miniconda_install.channels is defined and
        miniconda_install.user_home is defined
  tags:
    - 'miniconda_install_condarc'

# Check if conda install exists:
- name: 'miniconda install stat'
  stat:
    path: "{{ miniconda_install.path }}/bin/conda"
  register: miniconda_install_stat
  tags:
    - 'miniconda_install_stat'

# Download installer:
- name: 'miniconda install get installer'
  get_url:
    url: "{{ miniconda_mirror }}/{{ miniconda_installer }}"
    dest: "{{ miniconda_temp_dir }}/{{ miniconda_installer }}"
    mode: '0755'
  when: not miniconda_install_stat.stat.exists
  tags:
    - 'miniconda_install_get_installer'

# Install miniconda:
- name: 'miniconda install run installer'
  become_user: "{{ miniconda_install.user }}"
  command: "bash {{ miniconda_temp_dir }}/{{ miniconda_installer }} -b -p {{ miniconda_install.path }}"
  args:
    creates: "{{ miniconda_install.path }}"
  when: not miniconda_install_stat.stat.exists
  tags:
    - 'miniconda_install_run_installer'
