---

# install:
- name: 'miniconda install'
  include_tasks:
    file: 'install.yml'
    apply:
      tags:
        - 'install'
        - 'miniconda'
        - 'miniconda_install'
  loop: "{{ miniconda_installs }}"
  loop_control:
    loop_var: 'miniconda_install'
  when: miniconda_installs is defined
  tags:
    - 'always'
    - 'install'
    - 'miniconda'
    - 'miniconda_install'

# configure:
- name: 'miniconda configure'
  include_tasks:
    file: 'configure.yml'
    apply:
      tags:
        - 'configure'
        - 'miniconda'
        - 'miniconda_configure'
  loop: "{{ miniconda_installs }}"
  loop_control:
    loop_var: 'miniconda_install'
  when: miniconda_installs is defined
  tags:
    - 'always'
    - 'install'
    - 'miniconda'
    - 'miniconda_configure'

# tidy:
- name: 'miniconda tidy remove installer'
  file:
    path: "{{ miniconda_temp_dir }}/{{ miniconda_installer }}"
    state: 'absent'
  tags:
    - 'miniconda'
    - 'miniconda_tidy_remove_installer'
